http:
  host: 'localhost'
  port: 3000

db:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: '1234'
  database: 'store'
  synchronize: true
  logging: true

auth:
  header: 'authorization'
  secret: '5d01dc7f1b7e9fd5881339c956a44c835e48991f8c9d08a7a9d6d559eafa09ef'
  accessExpiryTime: 5m
  refreshExpiryTime: 7d
